### ISSUE TITLE
很好

### ISSUE THREAD

**Issue by cidj** [nakrakiiya/mefcl#1]
看起来很强大的样子，下来试试。多谢！

**Comment by hckjsnzf** [comment]
能传到国内不..
github下载太慢了..10几k.
想试用下啊,谢谢

**Comment by nakrakiiya** [comment]
传到哪？

其实你不需要clone（不过我git clone可以达到几百k），可以直接用迅雷下载打包好的（页面有，写着“.zip”字样的地方）。
在 2013-3-18 上午9:53，"hckjsnzf" notifications@github.com写道：

**Comment by hckjsnzf** [comment]
回复很快嘛..
我就是直接下压缩包的 https://github.com/nakrakiiya/mefcl-releases/archive/0.2rc1.zip

可以上传到百度网盘啊.

用迅雷..对github不好吧.

**Comment by nakrakiiya** [comment]
如果一次下载后就被服务器缓存了。如果这样，问题应该不大。
在 2013-3-18 下午12:00，"hckjsnzf" notifications@github.com写道：

**Comment by nakrakiiya** [comment]
好的，我想办法弄一下。
在 2013-3-18 下午12:00，"hckjsnzf" notifications@github.com写道：

**Comment by cidj** [comment]
初步用了一下，感觉 很好用。多谢了。
有问题会进一步汇报 。
另：使用迅雷会下载很快 ，十几分钟就好了。

2013/3/18 hckjsnzf notifications@github.com

**Comment by nakrakiiya** [comment]
欢迎反馈bug 。

我已发现几个，回头放出补丁。
在 2013-3-19 上午10:52，"cidj" notifications@github.com写道：

**Comment by hckjsnzf** [comment]
呵呵.
我电脑上没迅雷,我也不想装它.

**Comment by nakrakiiya** [comment]
无论怎样注册，百度网盘只会对我说：“注册时发生未知错误”，或者，干脆在我点“注册”的时候，没有任何反应。试了2天，换了不同内核的浏览器，都是同样结果。

```
 Best regards,
```

Xiaofeng Yang

在 2013年3月18日下午12:00，hckjsnzf notifications@github.com写道：

**Comment by hckjsnzf** [comment]
用户名  mefcl_mefcl@126.com
密码     mefclmefcl

请上传下.哈哈..

百度网盘在国内网盘的速度还算可以,广告也少

**Comment by cidj** [comment]
百度网盘不用安装客户端或者使用迅雷之类的下载工具直接就可以很快下载吗？

2013/3/20 hckjsnzf notifications@github.com

**Comment by hckjsnzf** [comment]
我都是firefox直接下载..速度1m-2m
可能上传大文件要个插件的

**Comment by nakrakiiya** [comment]
http://pan.baidu.com/share/link?shareid=559057&uk=120966731

```
 Best regards,
```

Xiaofeng Yang

在 2013年3月20日上午11:34，cidj notifications@github.com写道：

**Comment by nakrakiiya** [comment]
已上传：
http://pan.baidu.com/share/link?shareid=559057&uk=120966731

另，这里给出了补丁，这个补丁打了以后就可以在一个目录里面搜索某个关键字了
https://github.com/nakrakiiya/mefcl-releases/tree/be2837b7adb27dbc9fbdce0b8b83317c60afd5a3/patch

```
 Best regards,
```

Xiaofeng Yang

在 2013年3月20日上午11:34，cidj notifications@github.com写道：

**Comment by hckjsnzf** [comment]
不错,已经试用..
我去豆瓣推广下..
