### ISSUE TITLE
很不错。能否提过mac osx的版本？

### ISSUE THREAD

**Issue by ljd3000** [nakrakiiya/mefcl#2]

**Comment by nakrakiiya** [comment]
抱歉，我没用过Mac OS X.求指导。

你可以考虑下使用这个跟mefcl差不多的版本仓库，有朋友在Mac OS X下的GNU EMACS 24.3测试成功：
https://github.com/nakrakiiya/.emacs.d/

按照下面的步骤来做（假设你只做Common Lisp开发）：
- 安装GNU Emacs 24.3（我自己是在Linux下用24.2版本，有朋友在Mac OS X下的GNU EMACS
  24.3测试成功），但不要装任何第三方插件。
- 安装一个开源Common Lisp实现，比如，Clozure CL。
- 输入下面的命令（可能Mac OS X也是这样的命令吧）：

cd ~
git clone git://github.com/nakrakiiya/.emacs.d.git
ln -sfv .emacs.d/.emacs .emacs
- 用文本编辑器打开~/.emacs文件，修改里面这一行：

(setq inferior-lisp-program "~/ccl/lx86cl64") 将双引号部分修改成你安装的Common
Lisp实现的可执行文件的路径。
- 启动emacs。然后，M-x slime。如果想要启动emacs的时候自动启动slime repl，可以在.emacs最后加上一行：
  (slime)
  
   Best regards,
  Xiaofeng Yang

2013/3/27 ljd3000 notifications@github.com

**Comment by ljd3000** [comment]
多谢指导。
我试了一下，很好用，比我自己配置的好多了。
我只把缺省字体改为等宽的monaco　14号字体, ccl 改为sbcl。

我的环境是Emacs 24.3 + sbcl + quicklisp

**Comment by nakrakiiya** [comment]
忘了说要改字体了。抱歉
在 2013-3-27 下午2:48，"ljd3000" notifications@github.com写道：
