### ISSUE TITLE
請問如何添加emacs插件

### ISSUE THREAD

**Issue by kyunsiu** [nakrakiiya/mefcl#3]
自己平時也用emacs，但由於學藝未精，故不知如何在mefcl中添加插件，在哪個文件修改呢，多謝

**Comment by nakrakiiya** [comment]
​菜单里面：Options -> Manage Emacs
Packages。然后就会列出一些源里面的插件，然后，选择要安装的插件进行安装。注意Package菜单和鼠标中键的使用。一般不需要修改配置文件，直接重启生效。
如果需要做配置，请使用Options -> Customize Emacs。

不推荐的方法：通过修改emacs\home.emacs文件来修改配置，这一般只会将事情搞糟。.emacs其实是专为新手设计的（初衷就是为了让新手容易搞懂），所以内容非常容易搞清楚（起码0.1是这样的，0.2的时候这方面没有考虑太多，不过还好其实变化不会太大）。

如果你的mefcl是装在U盘里面的，那么请在安装完插件以后将emacs\home.emacs.d里面所有的.elc文件给删除，否则可能无法在别的电脑上用。
如果重启以后有的插件无法正常工作，那么也请删除所有的.elc文件，然后重启，也许这么一删，就能正常工作了。

在 2013-4-8 下午3:37，"kyunsiu" notifications@github.com写道：

**Comment by kyunsiu** [comment]
好啦，前一種方式我不會，我直接去改.emcas，加了個evil，現在基本滿意啦，希望菜單中能多加些功能，如編譯爲本地碼甚麼的，這點我一直搞不懂，多謝你給大家提供了這麼一個好平臺

**Comment by nakrakiiya** [comment]
不客气。我看找时间给个视频吧。万不得已，才要手工修改.emacs 。

你说的“编译成本地码”我该怎么理解？
 在 2013-4-9 上午10:53，"kyunsiu" notifications@github.com写道：

**Comment by kyunsiu** [comment]
不過emacs的菜單有時比.emacs更不直觀，本地碼就是可執行文件（我說的方法不對……）

**Comment by nakrakiiya** [comment]
common lisp -> exe ？？？

不是菜单呀。菜单点出来会有相应的设置界面呀。
在 2013-4-9 上午11:22，"kyunsiu" notifications@github.com写道：

**Comment by kyunsiu** [comment]
就是想要exe，對的對的，比如啟用evil我就覺得在.emacs中加一句話方便

**Comment by nakrakiiya** [comment]
你现在用的是哪个Common Lisp？每一个都有不同的方法，每一个的文档都会告诉你该怎么做。你先看看文档，如果需要，我再单独写一篇。

我刚刚看了下，evil在安装完以后，以后启动后都会自动加载（所以这部分代码就不用写了）。不过evil-mode默认不会启用（只需写这部分代码）。

```
 Best regards,
```

Xiaofeng Yang

2013/4/9 kyunsiu notifications@github.com

**Comment by kyunsiu** [comment]
我現在在用ccl，初學者而已，對了，怎麼把自動匹配括號完全去掉，很不習慣，註釋了autopair但有時函數定義那裡還是會自動個括號

**Comment by nakrakiiya** [comment]
CCL制作exe：
1. 在CCL里面加载你的程序。
2. 执行这一句：
(ccl:save-application "xxx.exe" :toplevel-function 主函数 :prepend-kernel t)

补充说明：
- 制作过程会随机性（小几率，如果是在EMACS里面几率可能会大一些）的崩溃导致生成的exe内容不正确。
- 生成EXE以后，CCL会自动退出。这时可以M-x slime来重新启动CCL。

你可以把.emacs下面的这些内容全部干掉：
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; autopair
(require 'autopair)
(require 'auto-pair+)
(add-hook 'emacs-lisp-mode-hook
          #'(lambda ()
              (push '(?`. ?')
                    (getf autopair-extra-pairs :comment))
              (push '(?` . ?')
                    (getf autopair-extra-pairs :string))))
(add-hook 'lisp-mode-hook
          #'(lambda ()
              (push '(?`. ?')
                    (getf autopair-extra-pairs :comment))
              (push '(?` . ?')
                    (getf autopair-extra-pairs :string))))
(add-hook 'c-mode-common-hook #'(lambda () (autopair-mode)))
(add-hook 'lisp-mode-hook #'(lambda () (autopair-mode)))
;(add-hook 'slime-repl-mode-hook #'(lambda () (autopair-mode)))
(add-hook 'emacs-lisp-mode-hook #'(lambda () (autopair-mode)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; indent when ENTER pressed in lisp mode
(defun my-newline-and-indent ()
  (interactive)
  (newline-and-indent)
  (slime-reindent-defun))
(define-key lisp-mode-shared-map (kbd "RET") 'my-newline-and-indent)

```
 Best regards,
```

Xiaofeng Yang

2013/4/10 kyunsiu notifications@github.com

**Comment by kyunsiu** [comment]
多谢啦，可以了

**Comment by nakrakiiya** [comment]
不客气
